language: php

php:
- '5.6'
- '7.0'
- '7.1'
- '7.2'
- '7.3'

install:
- composer install

addons:
  sonarcloud:
    organization: "cloudbluesonarcube"
    token:
      secure: "nEbC4XRHpK/SVxMeUQE8V0VFzhYx0la9/fFJTy3QL1gAsxxCA56DGNj5nEiLW9QvUEoujYO4RxTYICpnIzMJnQWX4vJObaTq62r3tHMNUe35L/l6asOXDtYFro5C9Zd+SEgUDY9y/YaWG6p1Ll52T6uQQxpwVHmoFMUr2ryuROeyzn8Fvzo31ZPDkK5LM4EPEplFa9hVP+2O1C7vDuQED4Uteghfh9bTbTQ7UOycB9QaJYwJ55Mg/IkSJq7WEeJCkOfYeBwv9kSLAc7lIwrOdxzZ/P7wyWjkzUkUKQq+JLE4O6xDYYk0jV3DzX7kqe8tB/aaIJpyvAi3/XVkIs9k9MWELY95qUmojk1EX4K7nzu8mXE/9U0ykOjBNetPmKBMGQ7xcywKY8NXyiuQjtwvNrlMH3Az+HafkIjVVuySU/MEoQ5lGWkKunsvbZfviBLSV5IJJxDybBZm2RYeHtu1CwOqW+FlepS7CsW8OXluu4oKsMJlsCVLmvzYvxZqIkOzTFyb4sflFvAShPhyIA8o0Jh69wL3azCHAtiKttkF5IzHSCj68xfXndZ0JeMxQAUli8J6YSYPHbQ/mEvoNM6R8VYA3C/UFXzu0E2cq96mrnhopVK0in76FJSZSrNresWRhLdRk7Anbc92zVBi07ttx/9o3wlipHOjM8TmyCbkAxU="

script:
- ./vendor/bin/phpunit -c ./phpunit.xml
- sonar-scanner

after_success:
- bash <(curl -s https://codecov.io/bash)
