dist: trusty
language: php
php:
- '5.6'
- '7.0'
- '7.1'
- '7.2'
- '7.3'
install:
- composer install
addons:
  sonarcloud:
    organization: "cloudbluesonarcube"
    token:
      secure: "WT8zFRhBle7Ig5aN0aXmQKFX09ywWe/NgZsREE/GXu0uRflY3U8RncvBupPWLgFipa2ELwwJb7ELKuUVIMzg1wsTQ+UbtuuOvp4ht7XkCzQAQvounfSUwXcBmKnLe5WSguDLCJw8jzvC50mVfp19xYncBwGYPlQVsIp/JW5YjXfDinUJRqARJv651vrruQwfB0VSe71r4eW0NgLrMVlYXTsHD8MDNSZG0mgVoCssJceliY8dzrMbeJwXoo4VYkhypL7hua9ejwT0gPxI+5KtDqKvzWfwWLAXhnMI7HgEN/+HVIKnzCDOhHb53MItVJefr7wf3hYCvojzVBEWeVvrGs40Ppo6ltPc0u2IX2LGTB80F4qzlciJib0fA+2CtUv3emGmFgEBCBezQAr+yYhcPQuzt7wNH2YsFI1o6oOd+SsL88PDFkpZiaMMoTt1DryRyPgyRoyYku0suziMnQcZS1S1D73UJNvUPQagVgnfLWl19Lsq1Rxom3v7DmJHXCystdhXlHDgNGnddSryOz01QDVww9IQNw3a76ncHB/Wb9yfuWdiaOVrT6tePsUMmhuqHowegzKOlhIdkXTuhfDhRuWngqcyBbo4vfBdkWx7m8MM/P/8L0Ms473J6J/VDwI4Bw6I7Jy3M3+nTDcQA9k/R8RDOaVm2Eg52Y+MBMtN6WU="
script:
- vendor/bin/phpunit -c coverage.xml --coverage-clover=coverage-report.clover --log-junit=test-report.xml
- sonar-scanner
after_success:
- bash <(curl -s https://codecov.io/bash)
