dist: trusty

language: php

php:
- '5.6'
- '7.0'
- '7.1'
- '7.2'
- '7.3'

install:
- composer install

addons:
  sonarcloud:
    organization: "cloudbluesonarcube"
    token:
      secure: "kkou1IsGWKUogK18ie6DSX8inp1XuT8Mmf7OMUEznnF/MwHB20hRbTR08HEAFEjnAJqTVRWNK4Q2ad0U0DoYaUaq317nOiKhCIWrtNJmzqqdtxMGn/39OPuXarq7Dn1YIoQUmaighp4r/WHdm9AsY5Q8yLXAP+ygo/jD/zSbVkVmLlJWUjiLrhnq+mv5JgqCr/BhApphnRnloCIiY2frZ0oVY1DfdugOl8YZbUXXpXiVgyxA1ZsDme7ArWhBXejq0FpxQ+YkuQXpKnM1XLS44K4PrjpRJXsr58Qai7BtjtVKbaifB2QEPjJ3Ta34m2kVcAKwpurZX/w6/w2C2n7T95ECYGklExgrlVi3VL2z/sV0U0++OExCvub54yokmpaBQRwQ+hEoHi+qep69WzWfJ4QIzDmgEgdLQn17HeNhaTgCUPRMw9LTpmTvsJ9aYUJoP3Tyq5ivp6G4RFdYvIyXPb+ZgnHA4iyn5SG2UlTQ3fcbdmsTpifOSRiqM4+mgjysRpXkmmIeVJ4ZPs9zwx1EPpGUf1jZyrJxuCcV/rGr7n8mNBTEzDUnfskirvdhxEqcN5XGqOl0zTI9AgTjjCroYlgT9N1Z9MlWY61gqYNBW4EviXUqR/z500020MPQWIP4y61Q450mo9ydNP4rLZKcPGI+OGjZB6te3WZ9vjxhcKs="

script:
- ./vendor/bin/phpunit -c ./phpunit.xml
- sonar-scanner

after_success:
- bash <(curl -s https://codecov.io/bash)
