language: php

php:
- '5.6'
- '7.0'
- '7.1'
- '7.2'
- '7.3'

install:
- composer install

addons:
  sonarcloud:
    organization: "cloudbluesonarcube"
    token:
      secure: "NdUdQCHbvs9juZlrwg8KAsJsm9JHUAsqKcKWz5spncE8grVEtD9uVI/2rXAC1b2AIasU6AaV8OIqIuXqbpd6hamNEl/KX45jOZk5OTIUoDQuSvbOp/8CTDG/7ST/MZ6nKnm/YJQGfoOLNSmjsRcw/FHGSSS+uiBkwjW/24tQpa9gNvUzHINaDOB/pXiYzJO4JrPFKor27VHyAlelF7zu4tHorBpuY/WU6JC4YL4rVpIN/6OTPaO3/hrQeTFTA71/1NhsD2SHqG17jWbdx6E2b0YNG8A+PpOFEjOT8MB2SN0138oD/KbUzPj6iUUy/PnR4J5UjA6xS63eMIIRhACqkq/fszLTZPCx/sa7VIZ9UwndJSI7+7dt7CELnKruPCJg46y1IzkqF6fb5vMQMSbvUi+BTtXYAa/c6AJ0/kk79XA8qCS9CdKC3aPVou9S3221HLfvBNt1rgNi23+nbY7J0I8r5IHcSmIiOnEZTcXbBDRGVspr/Fm98RG9uP4Z0D1+iVDcq7RRyABRvAv5QZUYc00fA+GDQ+p/fPMKaXydEobS04MJIzPVR9frCjbPNUgbEzegVAfdz8x0kse1Vb5dh1i9XtbEYbRfGoNn3gWDF2a4lp87z0mEdcPUzSJ+QfvNfysp9lT/eC7a8O7chWJ5m0hEHKcGZsI5Dc72Q9co0gI="

script:
- ./vendor/bin/phpunit -c ./phpunit.xml
- sonar-scanner

after_success:
- bash <(curl -s https://codecov.io/bash)
